# Generated by Django 3.2.16 on 2022-10-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
